### ISSUE TITLE
Database inconsistencies feedback

### ISSUE THREAD

**Issue by Solarer** [ungive/darktable-python#1]
Hey, I just tested the database inconsistencies on my desktop.

I encountered an exception in your darktable.py file line ~356 where you extract the timestamp from the image. I have a couple of images with no timestamp (value: None) so the division by 1000 failed with a TypeError. You might want to catch that exception.

Do you also extract color labels? There could also be inconsistencies in the color labels and it would also be nice to get a summary how many images do not have an XMP file but rating/color labels in the database. While this is not a conflict it could lead to data loss if one does not migrate the database file believing everything is backed up in the XMPs.
edit: ah sorry, you calculate the number of images without XMP files... but checking the labels would be great!

Is that something you would like to add? Thank you a lot for your effort!

**Comment by ungive** [comment]
Hey, thanks for your feedback!

I've added checks for color labels and also checks for the possibility of high ratings in XMP files only, while the database might contain 0 or 1 ratings. That isn't significant for backups, since the high rating is in the XMP, but can still be useful. Summary:

- Improved results and summary formatting
- Checking for color labels in addition to ratings
- Checking high XMP ratings as well, not only high database ratings
- Printing how many images have been checked

Example output now:

```
scanning database and xmp files. this could take a while...
...
no xmp files (286):
P1092909.JPG: no xmp file. version=0 path=C:\Photos\2024-07-09\P1092909.JPG
...
no rating in xmp files (5):
P1011907.RW2: no rating in xmp file. version=0 path=C:\Photos\2023-09-02\P1011907.RW2 xmp=P1011907.RW2.xmp database_rating=0
...
xmp rating inconsistent from database rating (18):
_1380684.JPG: inconsistent xmp rating. version=0 path=C:\Photos\2023-03-20\_1380684.JPG xmp=_1380684.JPG.xmp database_rating=3 xmp_rating=4
...
xmp color labels inconsistent from database color labels (2):
P1115601.RW2: inconsistent xmp color labels. version=0 path=C:\Photos\2024-09-25\P1115601.RW2 xmp=P1115601.RW2.xmp database_labels=[] xmp_labels=red

31918 total photos in library
2384 photos checked that either have a rating above 1 or color labels in either the database or the xmp file
WARN 286 photos have no xmp file
WARN 5 photos have no rating in their xmp file
WARN 18 photos have an xmp rating that is different from their database rating
WARN 2 photos have color labels that are inconsistent with their database color labels
BAD 311 inconsistencies found.
```

If everything's good:

```
GOOD your database and xmp files look consistent!
```

**Comment by ungive** [comment]
Don't be surprised if it runs a bit slower now, as it's reading a lot more XMP files now because of this change:

> Checking high XMP ratings as well, not only high database ratings

I've added a simple progress indication to show that it's doing something.
